#!/usr/bin/env python3
"""
Bundle all news JSON files into js/news-data-bundle.js
Run this script every time you add or update a news JSON file.

Usage:
    cd /path/to/robots-news
    python3 scripts/bundle.py
"""

import json
import os
import re

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR   = os.path.dirname(SCRIPT_DIR)
NEWS_DIR   = os.path.join(ROOT_DIR, 'news')
DATA_JS    = os.path.join(ROOT_DIR, 'js', 'data.js')
OUTPUT_JS  = os.path.join(ROOT_DIR, 'js', 'news-data-bundle.js')

# Read AVAILABLE_DATES from data.js
with open(DATA_JS, 'r') as f:
    data_js_content = f.read()

dates = re.findall(r"'(\d{4}-\d{2}-\d{2})'", data_js_content)
dates = list(dict.fromkeys(dates))  # deduplicate, preserve order
print(f"Found {len(dates)} dates in AVAILABLE_DATES: {dates}")

# Build bundle
lines = [
    '// Auto-generated by scripts/bundle.py — do not edit manually.',
    '// Edit the JSON files in news/ then re-run: python3 scripts/bundle.py',
    '',
    'window.__NEWS_DATA__ = window.__NEWS_DATA__ || {};',
    '',
]

loaded = 0
for date in dates:
    path = os.path.join(NEWS_DIR, f'{date}.json')
    if not os.path.exists(path):
        print(f'  SKIP {date} — file not found')
        continue
    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    js_data = json.dumps(data, ensure_ascii=False, separators=(',', ':'))
    lines.append(f'window.__NEWS_DATA__["{date}"] = {js_data};')
    lines.append('')
    loaded += 1
    print(f'  OK   {date} ({len(data.get("articles", []))} articles)')

with open(OUTPUT_JS, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

size_kb = os.path.getsize(OUTPUT_JS) / 1024
print(f'\nBundle written to js/news-data-bundle.js ({size_kb:.0f} KB, {loaded} dates)')
