#!/usr/bin/env python3
"""
Bundle news JSON files into per-locale JS bundles.

Output: js/bundles/news-bundle.<locale>.js
        window.__NEWS_DATA_LOCALES__["<locale>"]["YYYY-MM-DD"] = {...};

The en-US bundle also populates window.__NEWS_DATA__ for backwards compat.

Usage:
    python3 scripts/bundle.py                  # all discovered locales
    python3 scripts/bundle.py --locale zh-CN   # single locale only
    python3 scripts/bundle.py --locale en-US   # rebuild English bundle
"""

import json
import os
import re
import argparse

SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR    = os.path.dirname(SCRIPT_DIR)
NEWS_DIR    = os.path.join(ROOT_DIR, 'news')
DATA_JS     = os.path.join(ROOT_DIR, 'js', 'data.js')
BUNDLES_DIR = os.path.join(ROOT_DIR, 'js', 'bundles')

# ── Read AVAILABLE_DATES from data.js ────────────────────────────────────────
with open(DATA_JS, 'r', encoding='utf-8') as f:
    _data_js = f.read()

dates = list(dict.fromkeys(re.findall(r"'(\d{4}-\d{2}-\d{2})'", _data_js)))


def get_locales():
    """Discover available locales by scanning news/YYYY-MM-DD/ subdirectories."""
    locales = set()
    for date in dates:
        date_dir = os.path.join(NEWS_DIR, date)
        if os.path.isdir(date_dir):
            for fname in os.listdir(date_dir):
                if fname.endswith('.json'):
                    locales.add(fname[:-5])
    # Always include en-US (falls back to flat file if subdir missing)
    locales.add('en-US')
    return sorted(locales)


def find_json(date, locale):
    """
    Return path to the best available JSON for (date, locale).
    Priority:
      1. news/<date>/<locale>.json
      2. news/<date>.json  (flat legacy, only for en-US)
    Returns None if nothing found.
    """
    path = os.path.join(NEWS_DIR, date, f'{locale}.json')
    if os.path.exists(path):
        return path
    if locale == 'en-US':
        flat = os.path.join(NEWS_DIR, f'{date}.json')
        if os.path.exists(flat):
            return flat
    return None


def bundle_locale(locale):
    os.makedirs(BUNDLES_DIR, exist_ok=True)
    output_path = os.path.join(BUNDLES_DIR, f'news-bundle.{locale}.js')

    lines = [
        f'// Auto-generated by scripts/bundle.py — locale: {locale}',
        '// Do not edit manually. Re-run: python3 scripts/bundle.py --locale ' + locale,
        '',
        'window.__NEWS_DATA_LOCALES__ = window.__NEWS_DATA_LOCALES__ || {};',
        f'window.__NEWS_DATA_LOCALES__["{locale}"] = {{}};',
        '',
    ]

    loaded = 0
    for date in dates:
        path = find_json(date, locale)
        if not path:
            print(f'  SKIP {date}/{locale} — file not found')
            continue
        with open(path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        js_data = json.dumps(data, ensure_ascii=False, separators=(',', ':'))
        lines.append(f'window.__NEWS_DATA_LOCALES__["{locale}"]["{date}"] = {js_data};')
        lines.append('')
        loaded += 1
        print(f'  OK   {date}/{locale} ({len(data.get("articles", []))} articles)')

    # en-US: also populate legacy window.__NEWS_DATA__ for backwards compat
    if locale == 'en-US':
        lines += [
            '// Legacy compat: window.__NEWS_DATA__ for en-US',
            'window.__NEWS_DATA__ = window.__NEWS_DATA__ || {};',
        ]
        for date in dates:
            path = find_json(date, 'en-US')
            if not path:
                continue
            with open(path, 'r', encoding='utf-8') as f:
                data = json.load(f)
            js_data = json.dumps(data, ensure_ascii=False, separators=(',', ':'))
            lines.append(f'window.__NEWS_DATA__["{date}"] = {js_data};')
        lines.append('')

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    size_kb = os.path.getsize(output_path) / 1024
    print(f'  → {output_path} ({size_kb:.0f} KB, {loaded} dates)\n')
    return loaded


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Bundle news JSON into per-locale JS files.')
    parser.add_argument('--locale', help='Only bundle this locale (e.g. zh-CN)')
    args = parser.parse_args()

    print(f'Found {len(dates)} dates in AVAILABLE_DATES: {dates}')

    if args.locale:
        bundle_locale(args.locale)
    else:
        locales = get_locales()
        print(f'Discovered locales: {locales}\n')
        total = 0
        for locale in locales:
            total += bundle_locale(locale)
        print(f'Done. {len(locales)} locale bundles written to js/bundles/')
